import os
import json
from twilio.rest import Client as TwilioClient
from openai import OpenAI

# === Config paths
GARMIN_JSON_PATH = "garmin_export_all.json"

# === OpenAI Setup ===
OPENAI_API_KEY = os.environ["OPENAI_API_KEY"]

# === Twilio Setup ===
TWILIO_ACCOUNT_SID = os.environ["TWILIO_ACCOUNT_SID"]
TWILIO_AUTH_TOKEN = os.environ["TWILIO_AUTH_TOKEN"]
TWILIO_WHATSAPP_FROM = os.environ["TWILIO_WHATSAPP_FROM"]
TWILIO_WHATSAPP_TO = os.environ["TWILIO_WHATSAPP_TO"]

# === Load Garmin JSON
with open(GARMIN_JSON_PATH, "r") as f:
    full_data = json.load(f)

# === Extract only relevant fields
summary_input = {
    "date": full_data.get("date"),
    "steps": full_data.get("steps"),
    "sleep_summary": full_data.get("sleep", {}).get("dailySleepDTO", {}),
    "training_readiness": full_data.get("training_readiness"),
    "workout": full_data.get("workout"),
    "rhr": full_data.get("rhr"),
    "stress": full_data.get("stress"),
    "respiration": full_data.get("respiration"),
    "hydration": full_data.get("hydration"),
    "calories": full_data.get("calories"),
}

# === Prepare request
summary_text = json.dumps(summary_input, indent=2)

# === Initialize OpenAI Client
client = OpenAI(api_key=OPENAI_API_KEY)

response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {
            "role": "system",
            "content": (
                "You're an expert health assistant. Analyze this Garmin health data "
                "and summarize key insights in a motivational tone. Focus on sleep, recovery, and training readiness."
            )
        },
        {
            "role": "user",
            "content": summary_text
        }
    ],
    temperature=0.7,
)

summary = response.choices[0].message.content
print("📬 Summary generated by OpenAI:\n", summary)

# === Send via WhatsApp
twilio = TwilioClient(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN)

message = twilio.messages.create(
    body=summary,
    from_=FROM_WHATSAPP,
    to=TO_WHATSAPP
)

print(f"✅ WhatsApp message sent! SID: {message.sid}")
