from openai import OpenAI
from twilio.rest import Client
import json
import os

# === CONFIGURATION ===
GARMIN_JSON_PATH = "garmin_export_all.json"

# === OpenAI Setup ===
openai.api_key = os.environ["OPENAI_API_KEY"]

# === Twilio Setup ===
TWILIO_ACCOUNT_SID = os.environ["TWILIO_ACCOUNT_SID"]
TWILIO_AUTH_TOKEN = os.environ["TWILIO_AUTH_TOKEN"]
TWILIO_WHATSAPP_FROM = os.environ["TWILIO_WHATSAPP_FROM"]
TWILIO_WHATSAPP_TO = os.environ["TWILIO_WHATSAPP_TO"]

# === Load Garmin JSON
with open(GARMIN_JSON_PATH, "r") as f:
    garmin_data = json.load(f)

# === Compose message for OpenAI
daily_json_text = json.dumps(garmin_data, indent=2)

# === Initialize OpenAI Client (new SDK syntax)
client = OpenAI(api_key=OPENAI_API_KEY)

response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {
            "role": "system",
            "content": (
                "You're an expert health assistant. Analyze this Garmin health data "
                "and summarize key insights in a motivational tone. Focus on sleep, stress, training, and daily recovery."
            )
        },
        {
            "role": "user",
            "content": daily_json_text
        }
    ],
    temperature=0.7,
)

summary = response.choices[0].message.content
print("📬 Summary generated by OpenAI:\n", summary)

# === Send summary via WhatsApp (Twilio)
twilio = TwilioClient(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN)

message = twilio.messages.create(
    body=summary,
    from_=FROM_WHATSAPP,
    to=TO_WHATSAPP
)

print(f"✅ WhatsApp message sent! SID: {message.sid}")
