name: Garmin Summary Automation

on:
  schedule:
    - cron: '45 10 * * *'  # Runs daily at 7:45 AM BRT (10:45 UTC)
  workflow_dispatch:

jobs:
  summarize:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      FROM_WHATSAPP: ${{ secrets.TWILIO_WHATSAPP_FROM }}
      TO_WHATSAPP: ${{ secrets.TWILIO_WHATSAPP_TO }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install openai twilio

      - name: Load Garmin JSON summary
        run: python main.py
