name: Daily Garmin Summary

on:
  schedule:
    - cron: "45 10 * * *" # 7:45AM BRT = 10:45 UTC
  workflow_dispatch:

jobs:
  daily:
    runs-on: ubuntu-latest
    env:
      GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
      GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_WHATSAPP_FROM: ${{ secrets.TWILIO_WHATSAPP_FROM }}
      TWILIO_WHATSAPP_TO: ${{ secrets.TWILIO_WHATSAPP_TO }}
      OAUTH1_B64: ${{ secrets.OAUTH1_B64 }}
      OAUTH2_B64: ${{ secrets.OAUTH2_B64 }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements-dev.txt -r requirements-test.txt

      - name: Restore Garmin OAuth Tokens
        run: python fix_token.py
        
      - name: Run Garmin export
        run: python garmin_export_all.py

      - name: Run OpenAI + Twilio summary
        run: python main.py
